#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
echo 'Starting prettier...'
npx pretty-quick --staged

# lint-stages
echo 'Starting eslint...'
npx lint-staged "$1"

# commitizen
echo 'Starting commitlint...'
npx --no-install commitlint --edit $1

# If everything passes... Now we can commit
echo '✅✅✅✅ Excellent all test passed, I am committing this now. ✅✅✅✅'
