#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
npx pretty-quick --staged || (
  echo "Prettier tests failed"
  false
)

# lint-stages
npx lint-staged||
(
  echo "Eslint tests failed"
  false
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Excellent all test passed, I am committing this now. ✅✅✅✅'
