#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
npx pretty-quick --staged

# lint-stages
npx lint-staged||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)
